### ISSUE TITLE
Listen All events: list index out of range

### ISSUE THREAD

**Issue by vp1100** [streltsovdenis/pyami_asterisk#10]
Hi, I'm trying to listen to incoming SMS in yeastar and have the following incoming message:

> Event: ReceivedSMS
> Privilege: all,smscommand
> ID:
> GsmSpan: 2
> Sender: +******
> Recvtime: 2023-02-11 01:17:36
> Index: 1
> Total: 1
> Smsc: +******
> Content: test message
> --END SMS EVENT--

And I receive the following error due to last string doesn't include ":"

> Traceback (most recent call last):
>   File "/var/lib/bots/sms_bot/test.py", line 22, in <module>
>     ami.connect()
>   File "/usr/local/lib/python3.9/site-packages/pyami_asterisk/client.py", line 234, in connect
>     asyncio.run(self.connect_ami())
>   File "/usr/lib64/python3.9/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/usr/lib64/python3.9/asyncio/base_events.py", line 647, in run_until_complete
>     return future.result()
>   File "/usr/local/lib/python3.9/site-packages/pyami_asterisk/client.py", line 72, in connect_ami
>     await self._event_listener()
>   File "/usr/local/lib/python3.9/site-packages/pyami_asterisk/client.py", line 148, in _event_listener
>     self._data.put_nowait(_convert_bytes_to_dict(data))
>   File "/usr/local/lib/python3.9/site-packages/pyami_asterisk/utils.py", line 15, in _convert_bytes_to_dict
>     respons[_.split(": ", 1)[0]] = _.split(": ", 1)[1]
> IndexError: list index out of range

Fixed by changes in utils.py from:

`respons[_.split(": ", 1)[0]] = _.split(": ", 1)[1]`

to:

```
try:
    respons[_.split(": ", 1)[0]] = _.split(": ", 1)[1]
except:
    respons[_.split(": ", 1)[0]] = '' 
```

**Comment by denisstreltsov** [comment]
Hello, this library has not been tested on Asterisk Call Manager\1.1. Event`ReceivedSMS` is currently missing from the [wiki.asterisk.org](https://wiki.asterisk.org/wiki/display/AST/Home) documentation. The documentation spells out the "header: value" syntax on the [page](https://wiki.asterisk.org/wiki/display/AST/AMI+Command+Syntax)
