### ISSUE TITLE
It is possible to call action in asyncio_task callback ?

### ISSUE THREAD

**Issue by hamstie** [streltsovdenis/pyami_asterisk#11]
Hello,
i modify the example and call a ping action inside asyncio_task  callback:

callback_ping_noasync() callback is working
callback_ping_async() inside refresh_tokens will never be called

```
import asyncio
import random
from pyami_asterisk import AMIClient

# this one is working
def callback_ping_noasync(response_ping):
    print("Non async ping OK", response_ping)

async def refresh_tokens(timeout=4):

    # this one is NOT working 
    def callback_ping_async(response_ping):
        print("async ping NOK", response_ping)


    """Example: Refresh tokens"""
    while True:
        print(random.randrange(0, 1000))
        await asyncio.sleep(timeout)
        ami.create_action({"Action": "Ping"}, callback_ping_async)

ami = AMIClient(host='127.0.0.1', port=5038, username='foo', secret='bar')
ami.create_asyncio_task(tasks=[refresh_tokens(timeout=2)])
ami.create_action({"Action": "Ping"}, callback_ping_noasync)
ami.connect()
```

**Comment by denisstreltsov** [comment]
Hello, in your example there is not a single registered event or repeating action and the callback_ping_noasync callback will be executed once. All callback_ping_async callbacks will run after any registered event or repeated action.

example:

``` python
import asyncio
import random

from pyami_asterisk import AMIClient


# this one is working
def callback_ping_noasync(response_ping):
    print("Non async ping OK", response_ping)


def all_events(ev):
    print(ev)


async def refresh_tokens(timeout=4):
    # this one is NOT working
    def callback_ping_async(response_ping):
        print("async ping NOK", response_ping)

    """Example: Refresh tokens"""
    while True:
        print(random.randrange(0, 1000))
        await asyncio.sleep(timeout)
        ami.create_action({"Action": "Ping"}, callback_ping_async)


ami = AMIClient(host=HOST, port=PORT, username=USERNAME, secret=SECRET)
ami.create_asyncio_task(tasks=[refresh_tokens(2)])
ami.create_action({"Action": "Ping"}, callback_ping_noasync)
ami.register_event(["*"], all_events)
ami.connect()
```

response example:
<img width="1504" alt="Снимок экрана 2023-12-13 в 11 39 09" src="https://github.com/streltsovdenis/pyami_asterisk/assets/64684838/24c40db2-e33c-43e1-b939-53e4641a125d">
<img width="1505" alt="Снимок экрана 2023-12-13 в 11 45 53" src="https://github.com/streltsovdenis/pyami_asterisk/assets/64684838/024ecfe4-bf11-4dfd-85bb-b1fd495fc294">

It's better not to perform actions inside `ami.create_asyncio_task(tasks=[refresh_tokens(2)])`
it's better to do something like this

``` python
import asyncio
import random

from pyami_asterisk import AMIClient


def callback_ping_noasync(response_ping):
    print("Non async ping OK", response_ping)


def callback_ping_async(response_ping):
    print("async ping NOK", response_ping)


async def refresh_tokens(timeout=4):
    # this one is NOT working
    # def callback_ping_async(response_ping):
    #     print("async ping NOK", response_ping)

    """Example: Refresh tokens"""
    while True:
        print(random.randrange(0, 1000))
        await asyncio.sleep(timeout)
        # ami.create_action({"Action": "Ping"}, callback_ping_async)


TIMEOUT = 2
ami = AMIClient(host=HOST, port=PORT, username=USERNAME, secret=SECRET)
ami.create_asyncio_task(tasks=[refresh_tokens(TIMEOUT)])
ami.create_action({"Action": "Ping"}, callback_ping_noasync)
ami.create_action({"Action": "Ping"}, callback_ping_async, repeat=TIMEOUT)
ami.connect()

```

**Comment by hamstie** [comment]
Thank you for the quick and detailed response. 
My idea was to create a state machine that I could have run in an Async Task. This would have sent actions to the Asterisk server. I could have also operated the state machine via a ping/pong action, but in the event of a server failure, it would have stopped.

**Comment by denisstreltsov** [comment]
Hello, maybe this example will suit you. Send single ping

``` python
import asyncio
import random

from pyami_asterisk import AMIClient

ami = AMIClient(host=HOST, port=PORT, username=USERNAME, secret=SECRET, ping_delay=0, reconnect_timeout=0)


async def refresh_tokens(timeout=4):
    def callback_ping_async(response_ping):
        print("async ping NOK", response_ping)

    while True:
        print(random.randrange(0, 1000))
        await asyncio.sleep(timeout)
        ami.create_action({"Action": "Ping"}, callback_ping_async)
        await ami.connect_ami()


asyncio.run(refresh_tokens(2))
```

**Comment by hamstie** [comment]
Hello,
i need a looped state machine inside an async task that will be process actions immediately, 
your example will be re-connect each loop?
Is it possible to add a function like this: ami.reuse_asyncio_task() called inside 
the task function but after task return the created actions inside the task will be processed:

```
async def my_async_task(tmo=4):

    def callback_ping_async_task(response_ping):
        print("task ping", response_ping)

    ami.create_action({"Action": "Ping"}, callback_ping_async_task)
    tmo = random.randrange(0, 5)
    print("sleep:" + str (tmo))
    await asyncio.sleep(tmo)
    ami.reuse_asyncio_task() # reuse this task after return
```
or is it possible to send queued actions after my_async_task returns by default ?

**Comment by denisstreltsov** [comment]
Hello, you can rebuild your logic based on `ami.create_action({"Action": "Ping"}, callback_ping_async, repeat=TIMEOUT)` with `repeat`

``` python
import asyncio

from pyami_asterisk import AMIClient

TIMEOUT = 2


async def my_async_task(event):
    print("response event", event)
    await asyncio.sleep(0.5)
    print("example after sleep")


ami = AMIClient(host=HOST, port=PORT, username=USERNAME, secret=SECRET)
ami.create_action({"Action": "Ping"}, my_async_task, repeat=TIMEOUT)
ami.connect()
```

**Comment by hamstie** [comment]
Hello, yes it works  but this is more or less polling. Example: i got an external software event (mqtt) to make a call, after that  i need to send an action to ami (immediately). With repeat TMO i have to wait for the next ping/pong. I am searching for a way to send action immediately.
Thanks for your patience

**Comment by denisstreltsov** [comment]
At the moment I don't plan to modify anything. In your example, when receiving external software events, I would raise a new connection every time (the connection is established instantly) and send an action.

**Comment by hamstie** [comment]
i  found a very simple solution:
i am calling  await ami._handler_tasks(False) after create_action and the action will be send immediately inside
async task. A api-wrapper function like action_flush(...) would be nice for an better understanding.

Thank you 

```

async def refresh_tokens(timeout=4):

    def callback_ping_async(response_ping):
        print("async ping", response_ping)

    """Example: Refresh tokens"""
    while True:
        print(random.randrange(0, 10))
        await asyncio.sleep(timeout)
        print('action')
        ami.create_action({"Action": "Ping"}, callback_ping_async)
        await ami._handler_tasks(False)


```
